#!/bin/bash

HOSTS="hosts.csv"
DATE=`date "+%Y%m%d"`
rm -rf skip_*.csv

if [ -e ${HOSTS} ]; then
  while read row; do
  IP=`echo ${row} | cut -d , -f 1`
  MODEL=`echo ${row} | cut -d , -f 2`
  USERNAME=`echo ${row} | cut -d , -f 3`
  PASSWORD=`echo ${row} | cut -d , -f 4`
  ENABLE=`echo ${row} | cut -d , -f 5`

  PING_CHECK=`ping -w 3 -c 1 ${IP} | grep -i "100% packet loss" | sed "s/\r//"`

  if [ -n "$PING_CHECK" ]; then
    echo " ${IP} is stop." >> skip_${DATE}.csv
  else
  if [ ${MODEL} = "yamaha" ]; then
    ADMIN="administrator"
    SHRUN="show config"
    SHENV="show environment"
    END="exit"

    expect -c "
    spawn telnet ${IP}
    expect \"Username:\"
    send \"${USERNAME}\n\"
    expect \"Password:\"
    send \"${PASSWORD}\n\"
    expect \">\"
    send \"${ADMIN}\n\"
    expect \"Password:\"
    send \"${PASSWORD}\n\"
    expect \"#\"
    send \"${SHRUN}\n\"
    expect \"#\"
    send \"${SHENV}\n\"
    expect \"#\"
    send \"${END}\n\" ; sleep 1
    expect eof
        " > ${IP}_${MODEL}_${DATE}.log

  elif [ ${MODEL} = "alaxala" ]; then
    EN="enable"
    TERLEN="set terminal pager disable"
    SHOWRUN="show running-config"
    SHVER="show version"
    SHSYS="show system"
    END="exit"

    expect -c "
    spawn telnet ${IP}
    expect \"login:\"
    send \"${USERNAME}\r\"
    expect \"Password:\"
    send \"${PASSWORD}\r\"
    expect \">\"
    send \"${EN}\r\"
    expect \"Password:\"
    send \"${ENABLE}\r\"
    expect \"#\"
    send \"${TERLEN}\r\"
    expect \"#\"
    send \"${SHOWRUN}\r\"
    expect \"#\"
    send \"${SHVER}\r\"
    expect \"#\"
    send \"${SHSYS}\r\"
    expect \"#\"
    send \"${END}\r\" ; sleep 1
    expect eof
    " > ${IP}_${MODEL}_${DATE}.log
  else
    ${MODEL} > unknownmodel_${DATE}.log

  fi
fi
done < ${HOSTS}
else
echo "File is not exist!"
fi
