#!/bin/sh

######################################
#2019/12/20_ver0.02作成 by hiratac
#★使い方★
#スクリプトと同一ディレクトリにホストリストファイルhosts.csvが必要
#hosts.csvの記法はIPアドレス,モデル名,ユーザ名,パスワード,enableパスワード
#対応モデルはyamahaとAlaxala、それ以外のモデル定義の場合は不明モデルリストに書き出してスキップする。
######################################

HOSTS="hosts.csv"
DATE=`date "+%Y%m%d"`
rm -rf skip_*.csv #skipリストがあれば削除。

if [ -e ${HOSTS} ]; then
        while read row; do
                IP=`echo ${row} | cut -d , -f 1`
                MODEL=`echo ${row} | cut -d , -f 2`
                USERNAME=`echo ${row} | cut -d , -f 3`
                PASSWORD=`echo ${row} | cut -d , -f 4`
                ENABLE=`echo ${row} | cut -d , -f 5`

                PING_CHECK=`ping -w 3 -c 1 ${IP} | grep -i "100% packet loss" | sed "s/\r//"`　#pingによる疎通確認

                if [ -n "$PING_CHECK" ]; then
                        echo " ${IP} is stop." >> skip_${DATE}.csv #ping応答なければスキップしskip_日付.csvに書き出す。
                else
                        if [ ${MODEL} = "yamaha" ]; then
                                ADMIN="administrator"
                                SHRUN="show config"
                                SHENV="show environment"
                                END="exit"

                                expect -c "
                                        spawn telnet ${IP}
                                        expect \"Username:\"
                                        send \"${USERNAME}\n\"
                                        expect \"Password:\"
                                        send \"${PASSWORD}\n\"
                                        expect \">\"
                                        send \"${ADMIN}\n\"
                                        expect \"Password:\"
                                        send \"${PASSWORD}\n\"
                                        expect \"#\"
                                        send \"${SHRUN}\n\"
                                        expect \"#\"
                                        send \"${SHENV}\n\"
                                        expect \"#\"
                                        send \"${END}\n\" ; sleep 1
                                        expect eof
                                " > ${IP}_${MODEL}_${DATE}.log
                        elif [ ${MODEL} = "alaxala" ]; then
                                EN="enable"
                                TERLEN="set terminal pager disable"
                                SHOWRUN="show running-config"
                                SHVER="show version"
                                SHSYS="show system"
                                END="exit"

                                expect -c "
                                        spawn telnet ${IP}
                                        expect \"login:\"
                                        send \"${USERNAME}\r\"
                                        expect \"Password:\"
                                        send \"${PASSWORD}\r\"
                                        expect \">\"
                                        send \"${EN}\r\"
                                        expect \"Password:\"
                                        send \"${ENABLE}\r\"
                                        expect \"#\"
                                        send \"${TERLEN}\r\"
                                        expect \"#\"
                                        send \"${SHOWRUN}\r\"
                                        expect \"#\"
                                        send \"${SHVER}\r\"
                                        expect \"#\"
                                        send \"${SHSYS}\r\"
                                        expect \"#\"
                                        send \"${END}\r\" ; sleep 1
                                        expect eof
                                " > ${IP}_${MODEL}_${DATE}.log
                        else
                        ${MODEL} > unknownmodel_${DATE}.log

                        fi
                fi
        done < ${HOSTS}
else
echo "File is not exist!"
fi
