#!/bin/bash
#ver0.1作成(191222)
#対応デバイスはalaxala,yamaha,ios
#収集リストを定義するホストリストファイル(hosts.csv)が必要。カンマ区切りで次のように記載{IP,MODEL,USERNAME,PASSWORD,ENABLE_PASSWORD}
#ping疎通のない装置はskipリストに書き出す。
#不明なデバイス名は不明デバイスリストに書き出す。

hosts="hosts.csv"
today=`date "+%Y%m%d"`
rm -rf skip_*.csv

#ホストリスト有無の判定処理
if [ -e ${hosts} ]; then
  while read hostline; do
    ipadd=`echo ${hostline} | cut -d , -f 1`
    modelname=`echo ${hostline} | cut -d , -f 2`
    username=`echo ${hostline} | cut -d , -f 3`
    loginpass=`echo ${hostline} | cut -d , -f 4`
    enablepass=`echo ${hostline} | cut -d , -f 5`

    pingcheck=`ping -w 3 -c 1 ${ipadd} | grep -i "100% packet loss" | sed "s/\r//"`

    #pingでホストへの疎通性を確認する処理、応答なければskipリストにIPを記載する。
    if [ -n "$pingcheck" ]; then 
      echo "${ipadd}" >> skip_${today}.csv
    else
    #モデル定義があるかの処理
      if [ ${modelname} = "yamaha" ]; then
      expect -c "
        spawn telnet ${ipadd}
        expect \"Username:\"
        send  \"${username}\n\"
        expect \"Password:\"
        send \"${loginpass}\n\"
        expect \">\"
        send \"administrator\n\"
        expect \"Password:\"
        send \"${enablepass}\n\"
        expect \"#\"
        send \"show config\n\"
        expect \"#\"
        send \"show environment\n\"
        expect \"#\"
        send \"exit\n\" ; sleep 1
        expect eof
        " > ${ipadd}_${modelname}_${today}.log
        
      elif [ ${modelname} = "alaxala" ]; then
      expect -c "
        spawn telnet ${ipadd}
        expect \"login:\"
        send  \"${username}\r\"
        expect \"Password:\"
        send \"${loginpass}\r\"
        expect \">\"
        send \"enable\r\"
        expect \"Password:\"
        send \"${enablepass}\r\"
        expect \"#\"
        send \"set terminal pager disable\r\"
        expect \"#\"
        send \"show running-config\r\"
        expect \"#\"
        send \"show version\r\"
        expect \"#\"
        send \"show system\r\"
        expect \"#\"
        send \"show environment\r\"
        expect \"#\"
        send \"exit\r\" ; sleep 1
        expect eof
        " > ${ipadd}_${modelname}_${today}.log

      elif [ ${modelname} = "ios" ]; then
      expect -c "
        spawn telnet ${ipadd}
        expect \"Username:\"
        send  \"${username}\n\"
        expect \"Password:\"
        send \"${loginpass}\n\"
        expect \">\"
        send \"enable\n\"
        expect \"Password:\"
        send \"${enablepass}\n\"
        expect \"#\"
        send \"terminal length 0\n\"
        expect \"#\"
        send \"show running-config\n\"
        expect \"#\"
        send \"show version\n\"
        expect \"#\"
        send \"show inventory\n\"
        expect \"#\"
        send \"exit\n\" ; sleep 1
        expect eof
        " > ${ipadd}_${modelname}_${today}.log

      else
      #定義されてないモデルは不明モデルリストに書き出す。
      echo ${modelname} > unknownmodel_${today}.log
        
      fi

    fi
  done < ${hosts}

else
  echo "Hostlistfile is not exist!" >&2
fi
